#!/bin/bash

factorize() {
    n=$1
    for (( i=2; i<=n/2; i++ )); do
        if (( n % i == 0 )); then
            echo "$n = $i * $(($n/i))"
            return
        fi
    done
    echo "$n = $n * 1"
}

n=4958

factorize $n
